name: gaussian_splatting
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio
  - pytorch-cuda=12.1
  - plyfile
  - tqdm
  - opencv
